### ISSUE TITLE
[Help] Managing the `UNISIM` library

### ISSUE THREAD

**Issue by pidgeon777** [vhdl-linter/vhdl-linter#508]
As the title says, an example showing how the Xilinx `UNISIM` library can be referenced in a project analyzed with `vhdl-linter` would be very appreciated.

The Xilinx `UNISIM` source files are usually available in the following folder:

`C:\Xilinx\Vivado\2023.2\data\vhdl\src\unisims`

So, I suppose the source files in it should be added to the `vhdl-linter` project file 
somehow?

**Comment by Nik-Sch** [comment]
The `paths.additional` field in the settings file is a list of paths that can be used for external libraries:
```yml
paths:
    additional:
        - 'C:\Xilinx\Vivado\2023.2\data\vhdl\src\unisims'
```
